### ISSUE TITLE
Accessory Icon IOS14

### ISSUE THREAD

**Issue by StephaneMora972** [anto2oo/homebridge-livebox-tv#1]
Hi, Anto,
First, Thanks for your amazing plugin !
Is it possible to declare this accessory as external in order to display the right TV icon in IOS14 ?
The same type of issue was exposed for this plugin https://github.com/lukasroegner/homebridge-philips-hue-sync-box/issues/23
and they solved it with exposing TV accessories are as external accessories

Hopfully this will be possible ;) I know everything is working propoerly and my "issue" is just a cosmetic thing ^^

keep the good job going !

**Comment by antoninguyot** [comment]
Should be fixed by https://github.com/anto2oo/homebridge-livebox-tv/commit/584ea32df67ad416f1a7849185d689bd08e0c6f8 in v0.3.0, feel free to try it out and let me if that worked for you

**Comment by StephaneMora972** [comment]
Works like a charm, thank you very much !


Le 28 janv. 2023 à 19:57, Antonin ***@***.***> a écrit :

﻿

Should be fixed by 584ea32<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fanto2oo%2Fhomebridge-livebox-tv%2Fcommit%2F584ea32df67ad416f1a7849185d689bd08e0c6f8&data=05%7C01%7C%7C8f505645fbf7488ec6f008db018b61cb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638105470374085593%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=NItqs8DHpOQ7IjTJPKz4uHc4Ax3ja6zCqQ22SnFy%2F5Q%3D&reserved=0> in v0.3.0, feel free to try it out and let me if that worked for you
